#!/bin/sh
#
# parse iptables log to see which countries have been blocked (logged)
#
#  iptables logging
#  $iptables -A INPUT -i $extif -p tcp -m limit --limit 1/s --dport 0:1024 -j LOG --log-prefix "iptables: "
#  $iptables -A INPUT -i $extif -p udp -m limit --limit 1/s --dport 0:1024 -j LOG --log-prefix "iptables: "

for ip in `sudo grep SRC /var/log/iptables.log  |sed -e 's/.*SRC=//' -e 's/ DST.*//'`; do
	geoiplookup $ip
done
